[package]
name = "bryl-derive"
description = "Derive macros for bryl fixed-width records"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
bryl-pattern.workspace = true
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[lints]
workspace = true
