[package]
name = "bryl"
description = "Declarative fixed-width record encoding and decoding"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
pretty_assertions.workspace = true

[lints]
workspace = true
