[package]
name = "bryl"
description = "Declarative fixed-width record encoding and decoding"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["fixed-width", "record", "encoding", "parser", "derive"]
categories = ["encoding", "parser-implementations"]

[dependencies]
bryl-derive.workspace = true
bryl-pattern.workspace = true
chrono.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
pretty_assertions.workspace = true
trybuild.workspace = true

[lints]
workspace = true
