[package]
name = "bryl-nacha"
description = "NACHA ACH file reading and writing"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["nacha", "ach", "banking", "fixed-width", "payments"]
categories = ["encoding", "parser-implementations", "finance"]
exclude = ["tests"]

[lib]
name = "nacha"

[dependencies]
bon.workspace = true
bryl.workspace = true
chrono = { workspace = true, features = ["clock"] }
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
proptest.workspace = true

[lints]
workspace = true
