[package]
name = "bryl-metro2"
description = "Metro 2 credit reporting file reading and writing"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["metro2", "credit-reporting", "fixed-width", "cdia"]
categories = ["encoding", "parser-implementations", "finance"]
exclude = ["examples", "tests"]

[lib]
name = "metro2"

[dependencies]
bon.workspace = true
bryl.workspace = true
chrono.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
proptest.workspace = true

[lints]
workspace = true
